version: '3'
services:
  manager-postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_ecommerce
    ports:
      - "54321:5432"
  manager-postgres_transaction:
    build:
      context: ./transactions
      dockerfile: postgres_transaction.docker
    volumes:
      - ./storage/docker/postgres_transaction:/var/lib/postgresql/data
      - ./init:/var/init
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_transaction
    ports:
      - "54322:5432"
  manager-mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
      - ./test:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_DATABASE: voip
    ports:
      - "33062:3306"
#  manager-schema:
#    image: schemaspy/schemaspy
#    volumes:
#      - ./storage/schema:/output