version: '3'
services:
  manager-postgres_transaction:
    build:
      context: ./transactions
      dockerfile: postgres_transaction.docker
    volumes:
      - ./storage/docker/postgres_transaction:/var/lib/postgresql/data
      - ./init:/var/init
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_transaction
    ports:
      - "54322:5432"