version: '3'
services:
  manager-postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_ecommerce
    ports:
      - "54321:5432"
#  manager-schema:
#    image: schemaspy/schemaspy
#    volumes:
#      - ./storage/schema:/output