version: '3.5'
services:
  manager-postgres_sakila:
    image: postgres:11.3-alpine
    volumes:
      - ./storage/docker/sakila:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_sakila
    ports:
      - "54324:5432"