version: '3.5'
services:
  manager-postgres_transaction:
    image: postgres:11.3-alpine
    volumes:
      - ./storage/docker/postgres_transaction:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_transaction
    ports:
      - "54322:5432"