version: '3'
services:
  manager-postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: md
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: md_ecommerce
    ports:
      - "54321:5432"
  manager-mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
      - ./test/demo4/sql_dump:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_DATABASE: demo4
    ports:
      - "33061:3306"